//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Parameters) DeepCopyInto(out *Parameters) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Parameters.
func (in *Parameters) DeepCopy() *Parameters {
	if in == nil {
		return nil
	}
	out := new(Parameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Parameters) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParametersInitParameters) DeepCopyInto(out *ParametersInitParameters) {
	*out = *in
	if in.AllowOwnCredentialManagement != nil {
		in, out := &in.AllowOwnCredentialManagement, &out.AllowOwnCredentialManagement
		*out = new(bool)
		**out = **in
	}
	if in.MinimizePasswordLogin != nil {
		in, out := &in.MinimizePasswordLogin, &out.MinimizePasswordLogin
		*out = new(bool)
		**out = **in
	}
	if in.RateLimitBytesPerSecond != nil {
		in, out := &in.RateLimitBytesPerSecond, &out.RateLimitBytesPerSecond
		*out = new(float64)
		**out = **in
	}
	if in.SSHClientAuthKeyboardInteractive != nil {
		in, out := &in.SSHClientAuthKeyboardInteractive, &out.SSHClientAuthKeyboardInteractive
		*out = new(bool)
		**out = **in
	}
	if in.SSHClientAuthPassword != nil {
		in, out := &in.SSHClientAuthPassword, &out.SSHClientAuthPassword
		*out = new(bool)
		**out = **in
	}
	if in.SSHClientAuthPublickey != nil {
		in, out := &in.SSHClientAuthPublickey, &out.SSHClientAuthPublickey
		*out = new(bool)
		**out = **in
	}
	if in.ShowSessionMenu != nil {
		in, out := &in.ShowSessionMenu, &out.ShowSessionMenu
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParametersInitParameters.
func (in *ParametersInitParameters) DeepCopy() *ParametersInitParameters {
	if in == nil {
		return nil
	}
	out := new(ParametersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParametersList) DeepCopyInto(out *ParametersList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Parameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParametersList.
func (in *ParametersList) DeepCopy() *ParametersList {
	if in == nil {
		return nil
	}
	out := new(ParametersList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ParametersList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParametersObservation) DeepCopyInto(out *ParametersObservation) {
	*out = *in
	if in.AllowOwnCredentialManagement != nil {
		in, out := &in.AllowOwnCredentialManagement, &out.AllowOwnCredentialManagement
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.MinimizePasswordLogin != nil {
		in, out := &in.MinimizePasswordLogin, &out.MinimizePasswordLogin
		*out = new(bool)
		**out = **in
	}
	if in.RateLimitBytesPerSecond != nil {
		in, out := &in.RateLimitBytesPerSecond, &out.RateLimitBytesPerSecond
		*out = new(float64)
		**out = **in
	}
	if in.SSHClientAuthKeyboardInteractive != nil {
		in, out := &in.SSHClientAuthKeyboardInteractive, &out.SSHClientAuthKeyboardInteractive
		*out = new(bool)
		**out = **in
	}
	if in.SSHClientAuthPassword != nil {
		in, out := &in.SSHClientAuthPassword, &out.SSHClientAuthPassword
		*out = new(bool)
		**out = **in
	}
	if in.SSHClientAuthPublickey != nil {
		in, out := &in.SSHClientAuthPublickey, &out.SSHClientAuthPublickey
		*out = new(bool)
		**out = **in
	}
	if in.ShowSessionMenu != nil {
		in, out := &in.ShowSessionMenu, &out.ShowSessionMenu
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParametersObservation.
func (in *ParametersObservation) DeepCopy() *ParametersObservation {
	if in == nil {
		return nil
	}
	out := new(ParametersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParametersParameters) DeepCopyInto(out *ParametersParameters) {
	*out = *in
	if in.AllowOwnCredentialManagement != nil {
		in, out := &in.AllowOwnCredentialManagement, &out.AllowOwnCredentialManagement
		*out = new(bool)
		**out = **in
	}
	if in.MinimizePasswordLogin != nil {
		in, out := &in.MinimizePasswordLogin, &out.MinimizePasswordLogin
		*out = new(bool)
		**out = **in
	}
	if in.RateLimitBytesPerSecond != nil {
		in, out := &in.RateLimitBytesPerSecond, &out.RateLimitBytesPerSecond
		*out = new(float64)
		**out = **in
	}
	if in.SSHClientAuthKeyboardInteractive != nil {
		in, out := &in.SSHClientAuthKeyboardInteractive, &out.SSHClientAuthKeyboardInteractive
		*out = new(bool)
		**out = **in
	}
	if in.SSHClientAuthPassword != nil {
		in, out := &in.SSHClientAuthPassword, &out.SSHClientAuthPassword
		*out = new(bool)
		**out = **in
	}
	if in.SSHClientAuthPublickey != nil {
		in, out := &in.SSHClientAuthPublickey, &out.SSHClientAuthPublickey
		*out = new(bool)
		**out = **in
	}
	if in.ShowSessionMenu != nil {
		in, out := &in.ShowSessionMenu, &out.ShowSessionMenu
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParametersParameters.
func (in *ParametersParameters) DeepCopy() *ParametersParameters {
	if in == nil {
		return nil
	}
	out := new(ParametersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParametersSpec) DeepCopyInto(out *ParametersSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParametersSpec.
func (in *ParametersSpec) DeepCopy() *ParametersSpec {
	if in == nil {
		return nil
	}
	out := new(ParametersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParametersStatus) DeepCopyInto(out *ParametersStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParametersStatus.
func (in *ParametersStatus) DeepCopy() *ParametersStatus {
	if in == nil {
		return nil
	}
	out := new(ParametersStatus)
	in.DeepCopyInto(out)
	return out
}
