// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type TicketInitParameters struct {

	// (String) The description of the ticket.
	// The description of the ticket.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The expiry time of the ticket.
	// The expiry time of the ticket.
	Expiry *string `json:"expiry,omitempty" tf:"expiry,omitempty"`

	// (Number) The number of uses allowed for the ticket before it becomes invalid.
	// The number of uses allowed for the ticket before it becomes invalid.
	NumberOfUses *float64 `json:"numberOfUses,omitempty" tf:"number_of_uses,omitempty"`

	// (String) The name of the target the ticket grants access to.
	// The name of the target the ticket grants access to.
	TargetName *string `json:"targetName,omitempty" tf:"target_name,omitempty"`

	// (String) The user associated with the ticket. Will determine the permissions and access rights.
	// The user associated with the ticket. Will determine the permissions and access rights.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type TicketObservation struct {

	// (String) The description of the ticket.
	// The description of the ticket.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The expiry time of the ticket.
	// The expiry time of the ticket.
	Expiry *string `json:"expiry,omitempty" tf:"expiry,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) The number of uses allowed for the ticket before it becomes invalid.
	// The number of uses allowed for the ticket before it becomes invalid.
	NumberOfUses *float64 `json:"numberOfUses,omitempty" tf:"number_of_uses,omitempty"`

	// (String) The name of the target the ticket grants access to.
	// The name of the target the ticket grants access to.
	TargetName *string `json:"targetName,omitempty" tf:"target_name,omitempty"`

	// (String) The user associated with the ticket. Will determine the permissions and access rights.
	// The user associated with the ticket. Will determine the permissions and access rights.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type TicketParameters struct {

	// (String) The description of the ticket.
	// The description of the ticket.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The expiry time of the ticket.
	// The expiry time of the ticket.
	// +kubebuilder:validation:Optional
	Expiry *string `json:"expiry,omitempty" tf:"expiry,omitempty"`

	// (Number) The number of uses allowed for the ticket before it becomes invalid.
	// The number of uses allowed for the ticket before it becomes invalid.
	// +kubebuilder:validation:Optional
	NumberOfUses *float64 `json:"numberOfUses,omitempty" tf:"number_of_uses,omitempty"`

	// (String) The name of the target the ticket grants access to.
	// The name of the target the ticket grants access to.
	// +kubebuilder:validation:Optional
	TargetName *string `json:"targetName,omitempty" tf:"target_name,omitempty"`

	// (String) The user associated with the ticket. Will determine the permissions and access rights.
	// The user associated with the ticket. Will determine the permissions and access rights.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// TicketSpec defines the desired state of Ticket
type TicketSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TicketParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TicketInitParameters `json:"initProvider,omitempty"`
}

// TicketStatus defines the observed state of Ticket.
type TicketStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TicketObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Ticket is the Schema for the Tickets API. Manages a ticket in Warpgate. Tickets provide pre-authenticated access to a target for a specific user.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,warpgate}
type Ticket struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.targetName) || (has(self.initProvider) && has(self.initProvider.targetName))",message="spec.forProvider.targetName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   TicketSpec   `json:"spec"`
	Status TicketStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TicketList contains a list of Tickets
type TicketList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Ticket `json:"items"`
}

// Repository type metadata.
var (
	Ticket_Kind             = "Ticket"
	Ticket_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Ticket_Kind}.String()
	Ticket_KindAPIVersion   = Ticket_Kind + "." + CRDGroupVersion.String()
	Ticket_GroupVersionKind = CRDGroupVersion.WithKind(Ticket_Kind)
)

func init() {
	SchemeBuilder.Register(&Ticket{}, &TicketList{})
}
