apiVersion: parameters.warpgate.m.salami.network/v1alpha1
kind: Parameters
metadata:
  annotations:
    meta.upbound.io/example-id: parameters/v1alpha1/parameters
  labels:
    testing.upbound.io/example-name: global_settings
  name: global-settings
  namespace: crossplane-system
spec:
  forProvider:
    allowOwnCredentialManagement: true
    minimizePasswordLogin: false
    rateLimitBytesPerSecond: 1000000
    showSessionMenu: true
    sshClientAuthKeyboardInteractive: false
    sshClientAuthPassword: true
    sshClientAuthPublickey: true
