// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type SsoCredentialInitParameters struct {

	// The email address associated with the SSO provider. This should match the email address in the user's SSO provider account.
	// The email address associated with the SSO provider
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// The SSO provider name. Common values include google, github, okta, azure, or any custom SAML/OIDC provider configured in Warpgate.
	// The SSO provider name (e.g., 'google', 'github', 'okta')
	SsoProvider *string `json:"ssoProvider,omitempty" tf:"sso_provider,omitempty"`

	// The ID of the user to add the SSO credential to. Changing this forces a new resource to be created.
	// The ID of the user to add the SSO credential to
	// +crossplane:generate:reference:type=github.com/fulsiram/provider-upjet-warpgate/apis/namespaced/user/v1alpha1.User
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// Reference to a User in user to populate userId.
	// +kubebuilder:validation:Optional
	UserIDRef *v1.NamespacedReference `json:"userIdRef,omitempty" tf:"-"`

	// Selector for a User in user to populate userId.
	// +kubebuilder:validation:Optional
	UserIDSelector *v1.NamespacedSelector `json:"userIdSelector,omitempty" tf:"-"`
}

type SsoCredentialObservation struct {

	// The email address associated with the SSO provider. This should match the email address in the user's SSO provider account.
	// The email address associated with the SSO provider
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// The ID of the SSO credential.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The SSO provider name. Common values include google, github, okta, azure, or any custom SAML/OIDC provider configured in Warpgate.
	// The SSO provider name (e.g., 'google', 'github', 'okta')
	SsoProvider *string `json:"ssoProvider,omitempty" tf:"sso_provider,omitempty"`

	// The ID of the user to add the SSO credential to. Changing this forces a new resource to be created.
	// The ID of the user to add the SSO credential to
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type SsoCredentialParameters struct {

	// The email address associated with the SSO provider. This should match the email address in the user's SSO provider account.
	// The email address associated with the SSO provider
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// The SSO provider name. Common values include google, github, okta, azure, or any custom SAML/OIDC provider configured in Warpgate.
	// The SSO provider name (e.g., 'google', 'github', 'okta')
	// +kubebuilder:validation:Optional
	SsoProvider *string `json:"ssoProvider,omitempty" tf:"sso_provider,omitempty"`

	// The ID of the user to add the SSO credential to. Changing this forces a new resource to be created.
	// The ID of the user to add the SSO credential to
	// +crossplane:generate:reference:type=github.com/fulsiram/provider-upjet-warpgate/apis/namespaced/user/v1alpha1.User
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// Reference to a User in user to populate userId.
	// +kubebuilder:validation:Optional
	UserIDRef *v1.NamespacedReference `json:"userIdRef,omitempty" tf:"-"`

	// Selector for a User in user to populate userId.
	// +kubebuilder:validation:Optional
	UserIDSelector *v1.NamespacedSelector `json:"userIdSelector,omitempty" tf:"-"`
}

// SsoCredentialSpec defines the desired state of SsoCredential
type SsoCredentialSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SsoCredentialParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SsoCredentialInitParameters `json:"initProvider,omitempty"`
}

// SsoCredentialStatus defines the observed state of SsoCredential.
type SsoCredentialStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SsoCredentialObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SsoCredential is the Schema for the SsoCredentials API. Manages an SSO credential for a user in Warpgate.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,warpgate}
type SsoCredential struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.email) || (has(self.initProvider) && has(self.initProvider.email))",message="spec.forProvider.email is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ssoProvider) || (has(self.initProvider) && has(self.initProvider.ssoProvider))",message="spec.forProvider.ssoProvider is a required parameter"
	Spec   SsoCredentialSpec   `json:"spec"`
	Status SsoCredentialStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SsoCredentialList contains a list of SsoCredentials
type SsoCredentialList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SsoCredential `json:"items"`
}

// Repository type metadata.
var (
	SsoCredential_Kind             = "SsoCredential"
	SsoCredential_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SsoCredential_Kind}.String()
	SsoCredential_KindAPIVersion   = SsoCredential_Kind + "." + CRDGroupVersion.String()
	SsoCredential_GroupVersionKind = CRDGroupVersion.WithKind(SsoCredential_Kind)
)

func init() {
	SchemeBuilder.Register(&SsoCredential{}, &SsoCredentialList{})
}
