// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type UserRoleInitParameters struct {

	// The ID of the role to assign.
	// The ID of the role to assign
	// +crossplane:generate:reference:type=github.com/fulsiram/provider-upjet-warpgate/apis/namespaced/role/v1alpha1.Role
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// Reference to a Role in role to populate roleId.
	// +kubebuilder:validation:Optional
	RoleIDRef *v1.NamespacedReference `json:"roleIdRef,omitempty" tf:"-"`

	// Selector for a Role in role to populate roleId.
	// +kubebuilder:validation:Optional
	RoleIDSelector *v1.NamespacedSelector `json:"roleIdSelector,omitempty" tf:"-"`

	// The ID of the user to assign the role to.
	// The ID of the user to assign the role to
	// +crossplane:generate:reference:type=github.com/fulsiram/provider-upjet-warpgate/apis/namespaced/user/v1alpha1.User
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// Reference to a User in user to populate userId.
	// +kubebuilder:validation:Optional
	UserIDRef *v1.NamespacedReference `json:"userIdRef,omitempty" tf:"-"`

	// Selector for a User in user to populate userId.
	// +kubebuilder:validation:Optional
	UserIDSelector *v1.NamespacedSelector `json:"userIdSelector,omitempty" tf:"-"`
}

type UserRoleObservation struct {

	// The combined ID in the format user_id:role_id.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the role to assign.
	// The ID of the role to assign
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// The ID of the user to assign the role to.
	// The ID of the user to assign the role to
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type UserRoleParameters struct {

	// The ID of the role to assign.
	// The ID of the role to assign
	// +crossplane:generate:reference:type=github.com/fulsiram/provider-upjet-warpgate/apis/namespaced/role/v1alpha1.Role
	// +kubebuilder:validation:Optional
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// Reference to a Role in role to populate roleId.
	// +kubebuilder:validation:Optional
	RoleIDRef *v1.NamespacedReference `json:"roleIdRef,omitempty" tf:"-"`

	// Selector for a Role in role to populate roleId.
	// +kubebuilder:validation:Optional
	RoleIDSelector *v1.NamespacedSelector `json:"roleIdSelector,omitempty" tf:"-"`

	// The ID of the user to assign the role to.
	// The ID of the user to assign the role to
	// +crossplane:generate:reference:type=github.com/fulsiram/provider-upjet-warpgate/apis/namespaced/user/v1alpha1.User
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// Reference to a User in user to populate userId.
	// +kubebuilder:validation:Optional
	UserIDRef *v1.NamespacedReference `json:"userIdRef,omitempty" tf:"-"`

	// Selector for a User in user to populate userId.
	// +kubebuilder:validation:Optional
	UserIDSelector *v1.NamespacedSelector `json:"userIdSelector,omitempty" tf:"-"`
}

// UserRoleSpec defines the desired state of UserRole
type UserRoleSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            UserRoleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserRoleInitParameters `json:"initProvider,omitempty"`
}

// UserRoleStatus defines the observed state of UserRole.
type UserRoleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserRoleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// UserRole is the Schema for the UserRoles API. Creates an association between a user and a role in Warpgate.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,warpgate}
type UserRole struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              UserRoleSpec   `json:"spec"`
	Status            UserRoleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserRoleList contains a list of UserRoles
type UserRoleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UserRole `json:"items"`
}

// Repository type metadata.
var (
	UserRole_Kind             = "UserRole"
	UserRole_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UserRole_Kind}.String()
	UserRole_KindAPIVersion   = UserRole_Kind + "." + CRDGroupVersion.String()
	UserRole_GroupVersionKind = CRDGroupVersion.WithKind(UserRole_Kind)
)

func init() {
	SchemeBuilder.Register(&UserRole{}, &UserRoleList{})
}
