// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ParametersInitParameters struct {

	// Allow users to manage their own credentials.
	// Allow users to manage their own credentials
	AllowOwnCredentialManagement *bool `json:"allowOwnCredentialManagement,omitempty" tf:"allow_own_credential_management,omitempty"`

	// Minimize the use of password-based login methods.
	// When enabled, the username and password fields are hidden behind a link on the login page, with the focus on the SSO buttons.
	MinimizePasswordLogin *bool `json:"minimizePasswordLogin,omitempty" tf:"minimize_password_login,omitempty"`

	// Rate limit for data transfer in bytes per second.
	// Global bandwidth limit
	RateLimitBytesPerSecond *float64 `json:"rateLimitBytesPerSecond,omitempty" tf:"rate_limit_bytes_per_second,omitempty"`

	// Enable SSH keyboard interactive authentication for clients.
	// Enable SSH keyboard interactive authentication
	SSHClientAuthKeyboardInteractive *bool `json:"sshClientAuthKeyboardInteractive,omitempty" tf:"ssh_client_auth_keyboard_interactive,omitempty"`

	// Enable SSH password authentication for clients.
	// Enable SSH password authentication
	SSHClientAuthPassword *bool `json:"sshClientAuthPassword,omitempty" tf:"ssh_client_auth_password,omitempty"`

	// Enable SSH public key authentication for clients.
	// Enable SSH public key authentication
	SSHClientAuthPublickey *bool `json:"sshClientAuthPublickey,omitempty" tf:"ssh_client_auth_publickey,omitempty"`

	// When enabled, Warpgate injects a session menu into HTTP sessions, allowing users to log out or return to the home page.
	// When enabled, Warpgate injects a session menu into HTTP sessions, allowing users to log out or return to the home page.
	ShowSessionMenu *bool `json:"showSessionMenu,omitempty" tf:"show_session_menu,omitempty"`
}

type ParametersObservation struct {

	// Allow users to manage their own credentials.
	// Allow users to manage their own credentials
	AllowOwnCredentialManagement *bool `json:"allowOwnCredentialManagement,omitempty" tf:"allow_own_credential_management,omitempty"`

	// The ID of this resource (always set to "parameters").
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Minimize the use of password-based login methods.
	// When enabled, the username and password fields are hidden behind a link on the login page, with the focus on the SSO buttons.
	MinimizePasswordLogin *bool `json:"minimizePasswordLogin,omitempty" tf:"minimize_password_login,omitempty"`

	// Rate limit for data transfer in bytes per second.
	// Global bandwidth limit
	RateLimitBytesPerSecond *float64 `json:"rateLimitBytesPerSecond,omitempty" tf:"rate_limit_bytes_per_second,omitempty"`

	// Enable SSH keyboard interactive authentication for clients.
	// Enable SSH keyboard interactive authentication
	SSHClientAuthKeyboardInteractive *bool `json:"sshClientAuthKeyboardInteractive,omitempty" tf:"ssh_client_auth_keyboard_interactive,omitempty"`

	// Enable SSH password authentication for clients.
	// Enable SSH password authentication
	SSHClientAuthPassword *bool `json:"sshClientAuthPassword,omitempty" tf:"ssh_client_auth_password,omitempty"`

	// Enable SSH public key authentication for clients.
	// Enable SSH public key authentication
	SSHClientAuthPublickey *bool `json:"sshClientAuthPublickey,omitempty" tf:"ssh_client_auth_publickey,omitempty"`

	// When enabled, Warpgate injects a session menu into HTTP sessions, allowing users to log out or return to the home page.
	// When enabled, Warpgate injects a session menu into HTTP sessions, allowing users to log out or return to the home page.
	ShowSessionMenu *bool `json:"showSessionMenu,omitempty" tf:"show_session_menu,omitempty"`
}

type ParametersParameters struct {

	// Allow users to manage their own credentials.
	// Allow users to manage their own credentials
	// +kubebuilder:validation:Optional
	AllowOwnCredentialManagement *bool `json:"allowOwnCredentialManagement,omitempty" tf:"allow_own_credential_management,omitempty"`

	// Minimize the use of password-based login methods.
	// When enabled, the username and password fields are hidden behind a link on the login page, with the focus on the SSO buttons.
	// +kubebuilder:validation:Optional
	MinimizePasswordLogin *bool `json:"minimizePasswordLogin,omitempty" tf:"minimize_password_login,omitempty"`

	// Rate limit for data transfer in bytes per second.
	// Global bandwidth limit
	// +kubebuilder:validation:Optional
	RateLimitBytesPerSecond *float64 `json:"rateLimitBytesPerSecond,omitempty" tf:"rate_limit_bytes_per_second,omitempty"`

	// Enable SSH keyboard interactive authentication for clients.
	// Enable SSH keyboard interactive authentication
	// +kubebuilder:validation:Optional
	SSHClientAuthKeyboardInteractive *bool `json:"sshClientAuthKeyboardInteractive,omitempty" tf:"ssh_client_auth_keyboard_interactive,omitempty"`

	// Enable SSH password authentication for clients.
	// Enable SSH password authentication
	// +kubebuilder:validation:Optional
	SSHClientAuthPassword *bool `json:"sshClientAuthPassword,omitempty" tf:"ssh_client_auth_password,omitempty"`

	// Enable SSH public key authentication for clients.
	// Enable SSH public key authentication
	// +kubebuilder:validation:Optional
	SSHClientAuthPublickey *bool `json:"sshClientAuthPublickey,omitempty" tf:"ssh_client_auth_publickey,omitempty"`

	// When enabled, Warpgate injects a session menu into HTTP sessions, allowing users to log out or return to the home page.
	// When enabled, Warpgate injects a session menu into HTTP sessions, allowing users to log out or return to the home page.
	// +kubebuilder:validation:Optional
	ShowSessionMenu *bool `json:"showSessionMenu,omitempty" tf:"show_session_menu,omitempty"`
}

// ParametersSpec defines the desired state of Parameters
type ParametersSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ParametersParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ParametersInitParameters `json:"initProvider,omitempty"`
}

// ParametersStatus defines the observed state of Parameters.
type ParametersStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ParametersObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Parameters is the Schema for the Parameterss API. Manages global parameters in Warpgate. These settings control behavior across the entire Warpgate instance.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,warpgate}
type Parameters struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.allowOwnCredentialManagement) || (has(self.initProvider) && has(self.initProvider.allowOwnCredentialManagement))",message="spec.forProvider.allowOwnCredentialManagement is a required parameter"
	Spec   ParametersSpec   `json:"spec"`
	Status ParametersStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ParametersList contains a list of Parameterss
type ParametersList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Parameters `json:"items"`
}

// Repository type metadata.
var (
	Parameters_Kind             = "Parameters"
	Parameters_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Parameters_Kind}.String()
	Parameters_KindAPIVersion   = Parameters_Kind + "." + CRDGroupVersion.String()
	Parameters_GroupVersionKind = CRDGroupVersion.WithKind(Parameters_Kind)
)

func init() {
	SchemeBuilder.Register(&Parameters{}, &ParametersList{})
}
