// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type KeyCredentialInitParameters struct {

	// A descriptive label for the public key, helping to identify the key's purpose or origin.
	// A label for the public key
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// The OpenSSH format public key. This should be the public portion of an SSH keypair.
	// The OpenSSH public key
	PublicKey *string `json:"publicKey,omitempty" tf:"public_key,omitempty"`

	// The ID of the user to add the public key credential to. This cannot be changed after creation.
	// The ID of the user to add the public key credential to
	// +crossplane:generate:reference:type=github.com/fulsiram/provider-upjet-warpgate/apis/cluster/user/v1alpha1.User
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// Reference to a User in user to populate userId.
	// +kubebuilder:validation:Optional
	UserIDRef *v1.Reference `json:"userIdRef,omitempty" tf:"-"`

	// Selector for a User in user to populate userId.
	// +kubebuilder:validation:Optional
	UserIDSelector *v1.Selector `json:"userIdSelector,omitempty" tf:"-"`
}

type KeyCredentialObservation struct {

	// The date and time when the public key was added to the user's account.
	// The date the key was added
	DateAdded *string `json:"dateAdded,omitempty" tf:"date_added,omitempty"`

	// The combined ID in the format user_id:credential_id.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A descriptive label for the public key, helping to identify the key's purpose or origin.
	// A label for the public key
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// The date and time when the public key was last used for authentication, if available.
	// The date the key was last used
	LastUsed *string `json:"lastUsed,omitempty" tf:"last_used,omitempty"`

	// The OpenSSH format public key. This should be the public portion of an SSH keypair.
	// The OpenSSH public key
	PublicKey *string `json:"publicKey,omitempty" tf:"public_key,omitempty"`

	// The ID of the user to add the public key credential to. This cannot be changed after creation.
	// The ID of the user to add the public key credential to
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type KeyCredentialParameters struct {

	// A descriptive label for the public key, helping to identify the key's purpose or origin.
	// A label for the public key
	// +kubebuilder:validation:Optional
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// The OpenSSH format public key. This should be the public portion of an SSH keypair.
	// The OpenSSH public key
	// +kubebuilder:validation:Optional
	PublicKey *string `json:"publicKey,omitempty" tf:"public_key,omitempty"`

	// The ID of the user to add the public key credential to. This cannot be changed after creation.
	// The ID of the user to add the public key credential to
	// +crossplane:generate:reference:type=github.com/fulsiram/provider-upjet-warpgate/apis/cluster/user/v1alpha1.User
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// Reference to a User in user to populate userId.
	// +kubebuilder:validation:Optional
	UserIDRef *v1.Reference `json:"userIdRef,omitempty" tf:"-"`

	// Selector for a User in user to populate userId.
	// +kubebuilder:validation:Optional
	UserIDSelector *v1.Selector `json:"userIdSelector,omitempty" tf:"-"`
}

// KeyCredentialSpec defines the desired state of KeyCredential
type KeyCredentialSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     KeyCredentialParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider KeyCredentialInitParameters `json:"initProvider,omitempty"`
}

// KeyCredentialStatus defines the observed state of KeyCredential.
type KeyCredentialStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        KeyCredentialObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// KeyCredential is the Schema for the KeyCredentials API. Manages a public key credential for a user in Warpgate.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,warpgate}
type KeyCredential struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.label) || (has(self.initProvider) && has(self.initProvider.label))",message="spec.forProvider.label is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.publicKey) || (has(self.initProvider) && has(self.initProvider.publicKey))",message="spec.forProvider.publicKey is a required parameter"
	Spec   KeyCredentialSpec   `json:"spec"`
	Status KeyCredentialStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KeyCredentialList contains a list of KeyCredentials
type KeyCredentialList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KeyCredential `json:"items"`
}

// Repository type metadata.
var (
	KeyCredential_Kind             = "KeyCredential"
	KeyCredential_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: KeyCredential_Kind}.String()
	KeyCredential_KindAPIVersion   = KeyCredential_Kind + "." + CRDGroupVersion.String()
	KeyCredential_GroupVersionKind = CRDGroupVersion.WithKind(KeyCredential_Kind)
)

func init() {
	SchemeBuilder.Register(&KeyCredential{}, &KeyCredentialList{})
}
