// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type PasswordCredentialInitParameters struct {

	// The password to use for authentication. This is a sensitive value and will be stored only in state. This cannot be changed after creation, requiring recreation of the resource to update the password.
	// The password for authentication
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// The ID of the user to add the password credential to. This cannot be changed after creation.
	// The ID of the user to add the password credential to
	// +crossplane:generate:reference:type=github.com/fulsiram/provider-upjet-warpgate/apis/cluster/user/v1alpha1.User
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// Reference to a User in user to populate userId.
	// +kubebuilder:validation:Optional
	UserIDRef *v1.Reference `json:"userIdRef,omitempty" tf:"-"`

	// Selector for a User in user to populate userId.
	// +kubebuilder:validation:Optional
	UserIDSelector *v1.Selector `json:"userIdSelector,omitempty" tf:"-"`
}

type PasswordCredentialObservation struct {

	// The combined ID in the format user_id:credential_id.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the user to add the password credential to. This cannot be changed after creation.
	// The ID of the user to add the password credential to
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type PasswordCredentialParameters struct {

	// The password to use for authentication. This is a sensitive value and will be stored only in state. This cannot be changed after creation, requiring recreation of the resource to update the password.
	// The password for authentication
	// +kubebuilder:validation:Optional
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// The ID of the user to add the password credential to. This cannot be changed after creation.
	// The ID of the user to add the password credential to
	// +crossplane:generate:reference:type=github.com/fulsiram/provider-upjet-warpgate/apis/cluster/user/v1alpha1.User
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// Reference to a User in user to populate userId.
	// +kubebuilder:validation:Optional
	UserIDRef *v1.Reference `json:"userIdRef,omitempty" tf:"-"`

	// Selector for a User in user to populate userId.
	// +kubebuilder:validation:Optional
	UserIDSelector *v1.Selector `json:"userIdSelector,omitempty" tf:"-"`
}

// PasswordCredentialSpec defines the desired state of PasswordCredential
type PasswordCredentialSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PasswordCredentialParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PasswordCredentialInitParameters `json:"initProvider,omitempty"`
}

// PasswordCredentialStatus defines the observed state of PasswordCredential.
type PasswordCredentialStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PasswordCredentialObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PasswordCredential is the Schema for the PasswordCredentials API. Manages a password credential for a user in Warpgate.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,warpgate}
type PasswordCredential struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.passwordSecretRef)",message="spec.forProvider.passwordSecretRef is a required parameter"
	Spec   PasswordCredentialSpec   `json:"spec"`
	Status PasswordCredentialStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PasswordCredentialList contains a list of PasswordCredentials
type PasswordCredentialList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PasswordCredential `json:"items"`
}

// Repository type metadata.
var (
	PasswordCredential_Kind             = "PasswordCredential"
	PasswordCredential_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PasswordCredential_Kind}.String()
	PasswordCredential_KindAPIVersion   = PasswordCredential_Kind + "." + CRDGroupVersion.String()
	PasswordCredential_GroupVersionKind = CRDGroupVersion.WithKind(PasswordCredential_Kind)
)

func init() {
	SchemeBuilder.Register(&PasswordCredential{}, &PasswordCredentialList{})
}
