// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CredentialPolicyInitParameters struct {

	// List of credential types required for HTTP access. Valid values: Password, PublicKey, Totp, Sso, WebUserApproval.
	HTTP []*string `json:"http,omitempty" tf:"http,omitempty"`

	// List of credential types required for MySQL access. Valid values: Password, PublicKey, Totp, Sso, WebUserApproval.
	MySQL []*string `json:"mysql,omitempty" tf:"mysql,omitempty"`

	// List of credential types required for PostgreSQL access. Valid values: Password, PublicKey, Totp, Sso, WebUserApproval.
	Postgres []*string `json:"postgres,omitempty" tf:"postgres,omitempty"`

	// List of credential types required for SSH access. Valid values: Password, PublicKey, Totp, Sso, WebUserApproval.
	SSH []*string `json:"ssh,omitempty" tf:"ssh,omitempty"`
}

type CredentialPolicyObservation struct {

	// List of credential types required for HTTP access. Valid values: Password, PublicKey, Totp, Sso, WebUserApproval.
	HTTP []*string `json:"http,omitempty" tf:"http,omitempty"`

	// List of credential types required for MySQL access. Valid values: Password, PublicKey, Totp, Sso, WebUserApproval.
	MySQL []*string `json:"mysql,omitempty" tf:"mysql,omitempty"`

	// List of credential types required for PostgreSQL access. Valid values: Password, PublicKey, Totp, Sso, WebUserApproval.
	Postgres []*string `json:"postgres,omitempty" tf:"postgres,omitempty"`

	// List of credential types required for SSH access. Valid values: Password, PublicKey, Totp, Sso, WebUserApproval.
	SSH []*string `json:"ssh,omitempty" tf:"ssh,omitempty"`
}

type CredentialPolicyParameters struct {

	// List of credential types required for HTTP access. Valid values: Password, PublicKey, Totp, Sso, WebUserApproval.
	// +kubebuilder:validation:Optional
	HTTP []*string `json:"http,omitempty" tf:"http,omitempty"`

	// List of credential types required for MySQL access. Valid values: Password, PublicKey, Totp, Sso, WebUserApproval.
	// +kubebuilder:validation:Optional
	MySQL []*string `json:"mysql,omitempty" tf:"mysql,omitempty"`

	// List of credential types required for PostgreSQL access. Valid values: Password, PublicKey, Totp, Sso, WebUserApproval.
	// +kubebuilder:validation:Optional
	Postgres []*string `json:"postgres,omitempty" tf:"postgres,omitempty"`

	// List of credential types required for SSH access. Valid values: Password, PublicKey, Totp, Sso, WebUserApproval.
	// +kubebuilder:validation:Optional
	SSH []*string `json:"ssh,omitempty" tf:"ssh,omitempty"`
}

type UserInitParameters struct {

	// List of allowed IP ranges in CIDR notation (e.g. 10.0.0.0/8, 192.168.1.0/24, or a single IP like 1.2.3.4/32). If set, only connections from these IP ranges will be allowed for this user. Leave empty to allow all IPs.
	// List of allowed IP ranges in CIDR notation. If set, only connections from these IP ranges will be allowed for this user.
	AllowedIPRanges []*string `json:"allowedIpRanges,omitempty" tf:"allowed_ip_ranges,omitempty"`

	// A block that defines the credential policies for this user. This block can be defined at most once.
	// The credential policy for the user
	CredentialPolicy []CredentialPolicyInitParameters `json:"credentialPolicy,omitempty" tf:"credential_policy,omitempty"`

	// A human-readable description of the user.
	// The description of the user
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The username of the user. Must be unique within the Warpgate instance.
	// The username of the user
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type UserObservation struct {

	// List of allowed IP ranges in CIDR notation (e.g. 10.0.0.0/8, 192.168.1.0/24, or a single IP like 1.2.3.4/32). If set, only connections from these IP ranges will be allowed for this user. Leave empty to allow all IPs.
	// List of allowed IP ranges in CIDR notation. If set, only connections from these IP ranges will be allowed for this user.
	AllowedIPRanges []*string `json:"allowedIpRanges,omitempty" tf:"allowed_ip_ranges,omitempty"`

	// A block that defines the credential policies for this user. This block can be defined at most once.
	// The credential policy for the user
	CredentialPolicy []CredentialPolicyObservation `json:"credentialPolicy,omitempty" tf:"credential_policy,omitempty"`

	// A human-readable description of the user.
	// The description of the user
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the user.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The username of the user. Must be unique within the Warpgate instance.
	// The username of the user
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type UserParameters struct {

	// List of allowed IP ranges in CIDR notation (e.g. 10.0.0.0/8, 192.168.1.0/24, or a single IP like 1.2.3.4/32). If set, only connections from these IP ranges will be allowed for this user. Leave empty to allow all IPs.
	// List of allowed IP ranges in CIDR notation. If set, only connections from these IP ranges will be allowed for this user.
	// +kubebuilder:validation:Optional
	AllowedIPRanges []*string `json:"allowedIpRanges,omitempty" tf:"allowed_ip_ranges,omitempty"`

	// A block that defines the credential policies for this user. This block can be defined at most once.
	// The credential policy for the user
	// +kubebuilder:validation:Optional
	CredentialPolicy []CredentialPolicyParameters `json:"credentialPolicy,omitempty" tf:"credential_policy,omitempty"`

	// A human-readable description of the user.
	// The description of the user
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The username of the user. Must be unique within the Warpgate instance.
	// The username of the user
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// UserSpec defines the desired state of User
type UserSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     UserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserInitParameters `json:"initProvider,omitempty"`
}

// UserStatus defines the observed state of User.
type UserStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// User is the Schema for the Users API. Manages a user in Warpgate.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,warpgate}
type User struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   UserSpec   `json:"spec"`
	Status UserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserList contains a list of Users
type UserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []User `json:"items"`
}

// Repository type metadata.
var (
	User_Kind             = "User"
	User_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: User_Kind}.String()
	User_KindAPIVersion   = User_Kind + "." + CRDGroupVersion.String()
	User_GroupVersionKind = CRDGroupVersion.WithKind(User_Kind)
)

func init() {
	SchemeBuilder.Register(&User{}, &UserList{})
}
