apiVersion: user.warpgate.salami.network/v1alpha1
kind: SsoCredential
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/ssocredential
  labels:
    testing.upbound.io/example-name: john_google
  name: john-google
spec:
  forProvider:
    email: john.doe@company.com
    ssoProvider: google
    userIdSelector:
      matchLabels:
        testing.upbound.io/example-name: john_doe

---

apiVersion: user.warpgate.salami.network/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/ssocredential
  labels:
    testing.upbound.io/example-name: john_doe
  name: john-doe
spec:
  forProvider:
    credentialPolicy:
    - http:
      - Sso
      mysql:
      - Sso
      postgres:
      - Sso
      ssh:
      - Sso
      - PublicKey
    description: John Doe - Software Engineer
    username: john.doe
