apiVersion: user.warpgate.salami.network/v1alpha1
kind: PasswordCredential
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/passwordcredential
  labels:
    testing.upbound.io/example-name: eugene_password
  name: eugene-password
spec:
  forProvider:
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    userIdSelector:
      matchLabels:
        testing.upbound.io/example-name: eugene

---

apiVersion: user.warpgate.salami.network/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/passwordcredential
  labels:
    testing.upbound.io/example-name: eugene
  name: eugene
spec:
  forProvider:
    credentialPolicy:
    - http:
      - Password
      ssh:
      - Password
      - PublicKey
    username: eugene
